import { MdKeyboardArrowRight } from "react-icons/md";
import shoe from '@/assets/AllCategories/running-shoe.png';
import sunglass from '@/assets/AllCategories/sunglasses.png';
import necklace from '@/assets/AllCategories/pendant.png';
import watch from '@/assets/AllCategories/wristwatch.png';
import mobile from '@/assets/AllCategories/smartphone.png';
import electronic from '@/assets/AllCategories/responsive.png';
import cloth from '@/assets/AllCategories/clean-clothes.png';
import beauty from '@/assets/AllCategories/facial-massage.png';
import bag from '@/assets/AllCategories/briefcase.png';
export const categories = [
    {
      name: "Bag",
      subcategories: [
        "Purse",
        "bag",
        "Briefcases",
        "Money Clip ",
        "Wallet",
        "BackPack",
        "Travel Bag",
        "Card Holder",
        "Laptop Bag",
        "Cuitcase",
        "Hand Bag",
        "Gift Box",
      ],
      icon: bag,
      arrow: <MdKeyboardArrowRight />,
    },
    {
      name: "Beauty",
      subcategories: [
        "Eyeshadow",
    "Eyeliner",
    "Face Powder",
    "Makeup Remover",
    "Eye Brushes",
    "Hair Removal",
    "Mirror",
    "Teeth Whitening",
    "Nail Polish",
    "Lip Gloss",
    "Lip Liner",
    "Lipstick",
    "Lipstick",
    "Anti Hair Loss",
    "Hairspray",
    "Hair Dryer",
    "Hair Dye",
    "Hair Oil",
    "Shower Gel",
    "Candles",
    "Lotion",
    "Perfume",
    "Perfume Set",
    "Deodorant",
    "soap",
    "body-wash",
    "hair-conditioner",
    "toner",
    "facial-mask",
    "face-moisturizer",
    "face-serum",
    "sunscreen",
      ],
      icon: beauty,
      arrow: <MdKeyboardArrowRight />,
    },
    {
      name: "Cloth",
      subcategories: [
        "Casual Pants For Men",
        "Mens Jeans Pant",
        "Men Suit",
        "Leather Jackets For Men",
        "Trouser",
        "Shirt",
        "Shorts",
        "Tie Clip",
        "Mens Sweater",
        "Boxers",
        "Mens Hat",
        "socks-men",
        "tie-men",
        "bow-ties",
        "gloves",
      ],
      icon: cloth,
      arrow: <MdKeyboardArrowRight />,
    },
    {
      name: "Electronic",
      subcategories: [
        "electronics",
        "mobile-accessories",
        "gps-&-navigation",
        "speaker",
        "ecurity-&-surveillance",
        "tv",
        "projector",
      ],
      icon: electronic,
      arrow: <MdKeyboardArrowRight />,
    },
    {
      name: "Phone",
      subcategories: [
        "Xiaomi",
  "Apple",
  "Huawei",
  "Realme",
  "One Plus",
  "Samsung",
  "Google",
  "Vivo",
  "Nokia",
  "LG",
  "htc",
  "motorola",
  "htc"
      ],
      icon: mobile,
      arrow: <MdKeyboardArrowRight />,
    },
    {
      name: "Watches",
      subcategories: [
        "Watch",
        "Women Watch",
        "men Watches",
        "Smart Watch",
        "Apple Watch",
        "Fit Band",
        "Gshock"
      ],
      icon: watch,
      arrow: <MdKeyboardArrowRight />,
    },
    {
      name: "Necklace",
      subcategories: [
        "Bracelet",
        "Earrings",
        "Jewelry Case",
        "Necklace",
        "Bridal Jewelry",
        "Crown",
        "Pendant",
        "Bangle",
        "Ring",
        "Anklet",
        "Tiara",
        "belly-chain",
        "jewelry-box",
        "pin-brooch",
        "fashion-jewelry",
      ],
      icon: necklace,
      arrow: <MdKeyboardArrowRight />,
    },
    {
      name: "Sunglass",
      subcategories: [
        "sunglass",
        "women-sunglasses",
        "baby-sunglasses",
        "party-sunglass",
        "goggles",
      ],
      icon: sunglass,
      arrow: <MdKeyboardArrowRight />,
    },
    {
      name: "Shoes",
      subcategories: [
        "Man Shoes",
        "Man Boot",
        "Ladies shoes",
        "Ladies Boot",
        "High Heels",
        "Formal Shoes",
        "Running Shoes",
        "Causal Shoes",
        "Sandals",
        "Loafers",
        "Sports Shoes",
        "Baby Shoes",
        "Rain Boots",
        "Football Shoes",
        "Shippers",
        
      ],
      icon: shoe,
      arrow: <MdKeyboardArrowRight />,
    },
  ];
  export const deliveryMethods = [
    "Standard Shipping",
    "Express Shipping",
    "Overnight Shipping",
    "In-Store Pickup",
    "Curbside Pickup",
    "Same-Day Delivery",
    "Drone Delivery",
    "International Shipping"
];
export const countries = [
    "Bangladesh",
    "India",
    "United States",
    "Canada",
    "Australia",
    "United Kingdom",
    "China",
    "Japan",
    "Germany",
    "France",
    "Brazil",
    "South Africa",
    "Italy",
    "Russia",
    "Mexico"
];
export const divisions = [
    "Dhaka",
    "Chattogram",
    "Rajshahi",
    "Khulna",
    "Barishal",
    "Sylhet",
    "Rangpur",
    "Mymensingh"
];